### ISSUE TITLE
Box API response header changes that may affect your application

### ISSUE THREAD

**Issue by leik-software** [Pablo2309/simple-box-integration#6]
See explanation here: https://medium.com/box-developer-blog/box-api-response-header-changes-9ded989b04f0
Will these changes produce bugs? 
I see that here https://github.com/Ziggeo/simple-box-integration/blob/5f161ae500caf067d5925ae421a6edfcb3b7879c/src/Base/BoxResponse.php#L134
the Content-Type header is still with capitals.
I attach the email which I received from Box:
![Screenshot 2021-04-08 151303](https://user-images.githubusercontent.com/56190053/114032825-f80e8580-987c-11eb-960b-170729476f20.png)

**Comment by ntshcalleia** [comment]
Hi @leik-software, thanks for the heads up! I'll ask the team to look into it.
