### ISSUE TITLE
Notice: Undefined index: type in BoxMain.php

### ISSUE THREAD

**Issue by leik-software** [Pablo2309/simple-box-integration#9]
Version: 0.0.5
Error: php.WARNING: Notice: Undefined index: type {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: type at vendor/ziggeo/simple-box-integration/src/Base/BoxMain.php:814)

**Comment by Bane-D** [comment]
Hi,

Thank you for letting us know.

An update has been pushed that should address this. Please do try it out and let us know how it goes for you.

PS: It is likely that you got some strange answer at that point causing the value to not have the expected parameter. If this is the case, you will likely have an issue somewhere else in the code. If this does happen I would suggest saving the response you got as is to see more details.

Of course, happy to be wrong and that all is working fine for you with this update :)

**Comment by leik-software** [comment]
Hey. Thank you for the update. Did you forget to create a new version? I am not able to composer update.

**Comment by ntshcalleia** [comment]
Hi @leik-software, can you try again?

**Comment by leik-software** [comment]
Hi @ntshcalleia , composer won't update. I tried composer update ziggeo/simple-box-integration but it tells me there is nothing to update or install. I deleted vendor and installed again, but still have 0.0.5.

**Comment by ntshcalleia** [comment]
Sorry, I thought it was set to auto-update. It should be updated now. 🙂

**Comment by leik-software** [comment]
Work with 0.0.6. Thanks.
